/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "storage.h"

int main (int argc, char *argv[]) {
	if (argc != 4) {
		printf ("usage: ./%s <user> <msg id> -s <ip>", argv[0]);
		exit (1);
	}

	CLIENT *rpc;
	rpc = clnt_create(argv[4], MSG_STORE, MSG_STORE_V, "TCP");

	if (rpc == NULL) {
		printf("ERROR , SERVICE NOT AVAILABLE\n");
		exit(-1);
	}

	query_msg result;
        result.msg = malloc(256);
        result.md5 = malloc(32);
	enum clnt_stat retval;
	retval = query_1(argv[1], argv[2], &result, rpc);

	if(!strcmp(result.msg, "")) {
		printf("ERROR , MESSAGE  DOES  NOT  EXIST\n");
		exit(0);
	}

	printf("MESS: %s\nMD5: %s\n", result.msg, result.md5);

	exit (0);
}
