/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "storage.h"

int main (int argc, char *argv[]) {
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	char *rpc_address = "127.0.0.1";

	CLIENT *rpc;
	rpc = clnt_create(rpc_address, MSG_STORE, MSG_STORE_V, "TCP");

	if (rpc == NULL) {
		printf("ERROR , SERVICE NOT AVAILABLE");
		exit(-1);
	}

	query_msg result;
	enum clnt_stat retval;
	retval = query_1(argv[1], argv[2], &result, rpc);

	if(!strcmp(result.msg, "")) {
		printf("ERROR , MESSAGE  DOES  NOT  EXIST");
		exit(0);
	}

	printf("MESS: %s\nMD5: %s\n", result.msg, result.md5);

	exit (0);
}
