
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "service", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service {


    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "prnt_str")
    @RequestWrapper(localName = "prnt_str", targetNamespace = "http://ws/", className = "service.PrntStr")
    @ResponseWrapper(localName = "prnt_strResponse", targetNamespace = "http://ws/", className = "service.PrntStrResponse")
    @Action(input = "http://ws/service/prnt_strRequest", output = "http://ws/service/prnt_strResponse")
    public void prntStr(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
