/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _P3_H_RPCGEN
#define _P3_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


#define STR_SND 1
#define STR_SND_V 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINT_STR 1
extern  enum clnt_stat print_str_1(char *, int *, CLIENT *);
extern  bool_t print_str_1_svc(char *, int *, struct svc_req *);
extern int str_snd_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINT_STR 1
extern  enum clnt_stat print_str_1();
extern  bool_t print_str_1_svc();
extern int str_snd_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_P3_H_RPCGEN */
