/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "p3.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
print_str_1(char *str, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, PRINT_STR,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &str,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
