/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include "p3.h"

bool_t
print_str_1_svc(char *str, int *result,  struct svc_req *rqstp)
{
	bool_t retval;


	printf("%s\n", str);

	*result = 0;
	retval = TRUE;

	return retval;
}

int
str_snd_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
