
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "md5ServiceService", targetNamespace = "http://ws/", wsdlLocation = "file:/home/nacho/distrubutedAss/p1/client/Md5ServiceService.wsdl")
public class Md5ServiceService
    extends Service
{

    private final static URL MD5SERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MD5SERVICESERVICE_EXCEPTION;
    private final static QName MD5SERVICESERVICE_QNAME = new QName("http://ws/", "md5ServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/nacho/distrubutedAss/p1/client/Md5ServiceService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MD5SERVICESERVICE_WSDL_LOCATION = url;
        MD5SERVICESERVICE_EXCEPTION = e;
    }

    public Md5ServiceService() {
        super(__getWsdlLocation(), MD5SERVICESERVICE_QNAME);
    }

    public Md5ServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MD5SERVICESERVICE_QNAME, features);
    }

    public Md5ServiceService(URL wsdlLocation) {
        super(wsdlLocation, MD5SERVICESERVICE_QNAME);
    }

    public Md5ServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MD5SERVICESERVICE_QNAME, features);
    }

    public Md5ServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Md5ServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Md5Service
     */
    @WebEndpoint(name = "md5ServicePort")
    public Md5Service getMd5ServicePort() {
        return super.getPort(new QName("http://ws/", "md5ServicePort"), Md5Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Md5Service
     */
    @WebEndpoint(name = "md5ServicePort")
    public Md5Service getMd5ServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "md5ServicePort"), Md5Service.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MD5SERVICESERVICE_EXCEPTION!= null) {
            throw MD5SERVICESERVICE_EXCEPTION;
        }
        return MD5SERVICESERVICE_WSDL_LOCATION;
    }

}
