
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "md5ServiceService", targetNamespace = "http://ws/", wsdlLocation = "file:/home/100315434/distrubutedAss/p1/client/md5Service.wsdl")
public class Md5ServiceService
    extends Service
{

    private final static URL MD5SERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webservice.Md5ServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webservice.Md5ServiceService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/100315434/distrubutedAss/p1/client/md5Service.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/100315434/distrubutedAss/p1/client/md5Service.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MD5SERVICESERVICE_WSDL_LOCATION = url;
    }

    public Md5ServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Md5ServiceService() {
        super(MD5SERVICESERVICE_WSDL_LOCATION, new QName("http://ws/", "md5ServiceService"));
    }

    /**
     * 
     * @return
     *     returns Md5Service
     */
    @WebEndpoint(name = "md5ServicePort")
    public Md5Service getMd5ServicePort() {
        return super.getPort(new QName("http://ws/", "md5ServicePort"), Md5Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Md5Service
     */
    @WebEndpoint(name = "md5ServicePort")
    public Md5Service getMd5ServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "md5ServicePort"), Md5Service.class, features);
    }

}
