/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "storage.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
init_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, INIT, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
insert_1(char *sender, char *receiver, char *id, char *msg, char *md5, int *clnt_res,  CLIENT *clnt)
{
	insert_1_argument arg;
	arg.sender = sender;
	arg.receiver = receiver;
	arg.id = id;
	arg.msg = msg;
	arg.md5 = md5;
	return (clnt_call (clnt, INSERT, (xdrproc_t) xdr_insert_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
msg_n_1(char *sender, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, MSG_N,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &sender,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
query_1(char *user, char *id, query_msg *clnt_res,  CLIENT *clnt)
{
	query_1_argument arg;
	arg.user = user;
	arg.id = id;
	return (clnt_call (clnt, QUERY, (xdrproc_t) xdr_query_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_query_msg, (caddr_t) clnt_res,
		TIMEOUT));
}
