/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "storage.h"

bool_t
xdr_query_msg (XDR *xdrs, query_msg *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->msg, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->md5, 32))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_insert_1_argument (XDR *xdrs, insert_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->sender, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->receiver, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->id, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->msg, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->md5, 32))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_query_1_argument (XDR *xdrs, query_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->user, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->id, 255))
		 return FALSE;
	return TRUE;
}
